import PySimpleGUI as sg

BOARD_SIZE = 10
SHIP_SIZES = [5, 4, 3, 3, 2]

ROW_LABELS = [chr(ord("A") + index) for index in range(BOARD_SIZE)]
COLUMN_LABELS = [str(index + 1) for index in range(BOARD_SIZE)]

MODE_SINGLEPLAYER = "singleplayer"
MODE_MULTIPLAYER = "multiplayer"
MODE_LABELS = {
    MODE_SINGLEPLAYER: "Jednoosobowa",
    MODE_MULTIPLAYER: "Dwuosobowa",
}

APP_BACKGROUND = "#0B1220"
PANEL_BACKGROUND = "#101A2B"
CARD_BACKGROUND = "#16253D"
TEXT_PRIMARY = "#EAF2FF"
TEXT_SECONDARY = "#A9B7C9"
ACCENT_COLOR = "#4F9DF5"
ACCENT_TEXT = "#08111F"
SEA_COLOR = "#17324D"
SHIP_COLOR = "#355B87"
MISS_COLOR = "#D7E2EE"
HIT_COLOR = "#D24E4E"
PREVIEW_COLOR = "#5D9CEC"
PREVIEW_INVALID_COLOR = "#B05C5C"
EMPTY_TEXT_COLOR = "#F6FAFF"
MISS_TEXT_COLOR = "#102133"
HIT_TEXT_COLOR = "#FFFFFF"

BUTTON_PRIMARY_COLOR = (ACCENT_TEXT, ACCENT_COLOR)
BUTTON_SECONDARY_COLOR = (TEXT_PRIMARY, "#24344D")
BUTTON_DANGER_COLOR = (TEXT_PRIMARY, "#8B4B4B")

TITLE_FONT = ("Segoe UI", 26, "bold")
SUBTITLE_FONT = ("Segoe UI", 12, "bold")
BODY_FONT = ("Segoe UI", 11)
BUTTON_FONT = ("Segoe UI", 11, "bold")
BOARD_FONT = ("Consolas", 11, "bold")
BOARD_CELL_SIZE = (3, 1)
BOARD_FRAME_PAD = (12, 12)
BOARD_BUTTON_PAD = (1, 1)

_THEME_CONFIGURED = False


def configure_theme() -> None:
    global _THEME_CONFIGURED
    if _THEME_CONFIGURED:
        return

    sg.theme("DarkBlue3")
    _THEME_CONFIGURED = True
